# -*- mode: shell-script -*-

setopt ALIASES
setopt ALWAYS_LAST_PROMPT
setopt AUTO_CD
setopt AUTO_NAME_DIRS
setopt AUTO_LIST
setopt AUTO_MENU
setopt AUTO_PUSHD
setopt BAD_PATTERN
unsetopt BEEP
#setopt CHASE_DOTS
setopt COMPLETE_IN_WORD
setopt CORRECT
setopt EQUALS
setopt EXTENDED_GLOB
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_DUPS
setopt LIST_PACKED
setopt LIST_TYPES
setopt NOTIFY
setopt NULL_GLOB
setopt PROMPT_PERCENT
setopt PROMPT_SUBST
setopt WARN_CREATE_GLOBAL
